### PR TITLE
A Little Work ;)

### PR DESCRIPTION
**Pull request by Yeganloo**

### CODE REVIEW

**Comment by zippy1981** [comment]
I asked the author of this package to add a license to it. Would you will willing to license your changes under the MIT or BSD  license?

**Comment by Yeganloo** [comment]
yes of course, but it's depend on what license the owner select for the basic codes!
there is some features i plan to do for this project but if it be under BSD!

**Comment by luscoma** [comment]
I'll add the license it'll be MIT

**Comment by Yeganloo** [comment]
Thanks a lot :+1:

**Comment by zippy1981** [comment]
This is great!

**Pull request merged**
